# pqc_types.py — generated by PQC Scanner
# Placeholder PQC key type stubs using Python runtime-checkable Protocols.
# isinstance() checks work today via duck-typing; replace this file once
# a real PQC library ships class-based key types.
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class MLDSAPrivateKey(Protocol):
    """ML-DSA private key (NIST FIPS 204 digital signature)."""
    def sign(self, data: bytes) -> bytes: ...
    def public_key(self) -> MLDSAPublicKey: ...


@runtime_checkable
class MLDSAPublicKey(Protocol):
    """ML-DSA public key."""
    def verify(self, signature: bytes, data: bytes) -> None: ...


@runtime_checkable
class MLKEMPrivateKey(Protocol):
    """ML-KEM private key (NIST FIPS 203 key encapsulation)."""
    def decapsulate(self, ciphertext: bytes) -> bytes: ...
    def public_key(self) -> MLKEMPublicKey: ...


@runtime_checkable
class MLKEMPublicKey(Protocol):
    """ML-KEM public key."""
    def encapsulate(self) -> tuple[bytes, bytes]: ...  # returns (ciphertext, shared_secret)
